# Generated by Django 4.1.7 on 2023-02-25 13:48

import E_Shop_API.E_Shop_Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='photos', verbose_name='Photo')),
                ('price', models.FloatField(max_length=100000, validators=[E_Shop_API.E_Shop_Products.models.validate_negative], verbose_name='Price')),
                ('count', models.IntegerField(validators=[E_Shop_API.E_Shop_Products.models.validate_negative], verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
